# Generated by Django 3.2.4 on 2021-06-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_rename_notes_lesson_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
